Hat command added.
FallenVaders/fallenvaders-minecraft-plugin pull request #25
Opened 2022-05-27 10:30 UTC by Niiz9

Note: Apparemment y'a beaucoup de lignes qui ont disparues, alors que non ...

2022-05-27 17:28 UTC, Djaytan requested changes

2022-05-27 17:28 UTC, Djaytan commented on src/main/java/fr/fallenvaders/minecraft/plugin/controller/PlayerController.java
> -      @NotNull CommandSender commandSender, @NotNull Player targetedPlayer, boolean isGodActivated);
Reformater avec google-java-format

2022-05-27 17:28 UTC, Djaytan commented on src/main/java/fr/fallenvaders/minecraft/plugin/controller/PlayerController.java
> +import org.bukkit.inventory.ItemStack;
Import non utilisé

2022-05-27 17:28 UTC, Djaytan commented on src/main/java/fr/fallenvaders/minecraft/plugin/controller/PlayerControllerImpl.java
> +      messageController.sendErrorMessage(playerSender, essentialsMessages.noItemInHandHat());
Ce n'est pas une erreur : tout fonctionne correctement. Par contre, c'est un "failure" puisque l'utilisateur n'a pas manipulé la commande dans les bonnes conditions.
=> `sendFailureMessage`

```suggestion
      messageController.sendFailureMessage(playerSender, essentialsMessages.noItemInHandHat());
```

2022-05-27 17:29 UTC, Djaytan commented on src/main/java/fr/fallenvaders/minecraft/plugin/controller/PlayerControllerImpl.java
> +    if (itemInHand.getType().isAir()) {
J'apprends un truc avec le `isAir` :p

2022-05-27 18:06 UTC, Niiz9 commented on src/main/java/fr/fallenvaders/minecraft/plugin/controller/PlayerController.java
> +import org.bukkit.inventory.ItemStack;
Elle est utilisée ... ?
Ligne 216

2022-05-27 18:07 UTC, Niiz9 commented on src/main/java/fr/fallenvaders/minecraft/plugin/controller/PlayerControllerImpl.java
> +    if (itemInHand.getType().isAir()) {
Avec plaisir :p

2022-05-27 19:44 UTC, Djaytan requested changes

2022-05-27 19:44 UTC, Djaytan commented on src/main/java/fr/fallenvaders/minecraft/plugin/controller/PlayerControllerImpl.java
> +      messageController.sendErrorMessage(playerSender, essentialsMessages.noItemInHandHat());
Le changement n'a pas été appliqué

2022-05-27 21:04 UTC, Djaytan requested changes

2022-05-27 21:04 UTC, Djaytan commented on pom.xml
> +                    <source>16</source>
C'est de retour :s

2022-05-28 09:06 UTC, Djaytan approved these changes

2022-05-28 09:23 UTC, merged